env:
  node: true
  es6: true
  mocha: true

plugins:
  - haraka

parserOptions:
  ecmaVersion: 2017

extends:
  - eslint:recommended
  - plugin:haraka/recommended

root: true

rules:
  indent: [ error, 2, { SwitchCase: 1 } ]
  no-empty: [ error, { allowEmptyCatch: true }]

globals:
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
