name: Plugin Tests - Windows

on: [ push, pull_request ]

env:
  CI: true

jobs:

  ci-test-win:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 16 ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Plugin
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v3
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run test
